### ISSUE TITLE
Derivatives of eigenray propagation time w.r.t. Rx/Tx position

### ISSUE THREAD

**Issue by almcleanuk** [org-arl/UnderwaterAcoustics.jl#25]
Differentiable propagation modeling looks really interesting. I've previously use crude finite differencing on the output of Bellhop as a proof-of-concept, while recommending investigating the use of automatic differentiation.

I came across RaySolver and decided to try it. A particular case I'm interested in are derivatives of the propagation time along an eigenray w.r.t. Rx/Tx positions. The simplest case is the derrivative w.r.t range.

The attached code appears to sucessfully calculate the derivatives using finite differences (the results are at least a plausible magnitude). However, my attempt to calculate the derivative with ForwardDiff was unsucessful, with the code returning derivatives of zero. Am I doing something wrong?

[munk_single_range_ex1.jl](https://github.com/org-arl/UnderwaterAcoustics.jl/files/6749924/munk_single_range_ex1.txt)

The code is also **very** slow to run the first time. I was aware Julia had a compliation latency, but this was much more than I expected. I'm a Julia novice, but it looks like something odd is happening with memory allocation. Any Ideas?

```
julia> @time include("munk_single_range_ex1.jl")
1359.126200 seconds (5.80 G allocations: 513.957 GiB, 8.40% gc time)

julia> @time include("munk_single_range_ex1.jl")
  0.280822 seconds (830.31 k allocations: 55.448 MiB)
```

FWIW. I'm using an Intel Core i7 5820K @ 3.30GHz with 32GiB of RAM and an SSD drive running WIndows 10.

**Comment by almcleanuk** [comment]
Opps I mage a mistake in the code, the geometry doesn't have any eigenrays. This is more sensible:

```
using UnderwaterAcoustics
using Plots
using ForwardDiff
using FiniteDifferences
using Optim

# function returns eigenray time for given receiver range (and depth).
# Finds eigenray by performing search from given initial launchangle.
function fn(r, pm, tx, z, launchangle)
    rangemax = ForwardDiff.value(r)
    f = ϕ -> abs2(
        z - UnderwaterAcoustics.traceray(pm, tx, ϕ[1], rangemax).raypath[end][3]
        )
    soln = optimize(f, [launchangle], BFGS())
    UnderwaterAcoustics.traceray(pm, tx, soln.minimizer[1], rangemax).time
end

# Set up environment, model and source
env = UnderwaterEnvironment(
  seasurface = SeaState2,
  seabed = SandyClay,
  ssp = MunkSSP(),
  bathymetry = ConstantDepth(5000)
)

pm = RaySolver(env; nbeams=1000)

tx = AcousticSource(0.0, -100.0, 1000.0)

# Set up an example receiver position
range = 2000.0
z = -90.0

rx = AcousticReceiver(range, z)

# Find eignerays for nominal receiver position
rays = eigenrays(pm, tx, rx)

plot(env; sources=[tx], receivers=[rx], rays=rays, ylims=(-500,0))

# Finite difference model
fdm1 = central_fdm(5, 1)
fdm2 = central_fdm(5, 2)

# Loop over the eigenrays
for ray in rays
    println("-------------------")
    # g is a function that returns the eigenray time as a function of range.
    # It is used with an initial launchangle equal to the launchangle for an
    # eigenray at the nominal range.
    g = r -> fn(r, pm, tx, z, ray.launchangle)
    # Try to use ForwardDiff (automatic differentiation) to differentiate g
    dtdr_auto = ForwardDiff.derivative(g, range)
    # Use FiniteDifferences to differentiate g
    fd1 = fdm1(g, range)
    fd2 = fdm2(g, range)
    println("Ray: ", ray)
    println("dtdr_auto: ", dtdr_auto)
    println("dtdr: ", fd1)
    println("d2tdr2: ", fd2)
end
```
After it's compiled @time gives the following
```19.317586 seconds (15.80 M allocations: 1.030 GiB, 1.53% gc time)```

**Comment by mchitre** [comment]
Your code isn't quite in a runnable state -- perhaps a copy'n'paste problem.

Also you probably don't want to be using `traceray()` directly, as it is not an exported function (therefore considered private) and so subject to change anytime. You'd instead want to use the `eigenrays()`. Something like:

```julia
using UnderwaterAcoustics
using ForwardDiff

function g(r)
         env = UnderwaterEnvironment()
         pm = RaySolver(env)
         tx = AcousticSource(0.0, -5.0, 1000.0)
         rx = AcousticReceiver(r, -10.0)
         r = eigenrays(pm, tx, rx)
         r[5].time   # travel time along the 5th path
end

ForwardDiff.derivative(g, 100.0)
```

Unfortunately this code won't work yet, due to known issue https://github.com/org-arl/UnderwaterAcoustics.jl/issues/8.

Essentially, we currently can't take derivates for parameters that affect the launch angle of an eigenray due to the way the optimizer works (the iterative solution of an optimization with dual numbers is not a dual number). I'm looking at ways around it and have some ideas, but haven't had the time to implement yet.

You should be able to take derivatives against parameters that don't change angle. For example:

```julia
using UnderwaterAcoustics
using ForwardDiff

function g(f)
         env = UnderwaterEnvironment()
         pm = RaySolver(env)
         tx = AcousticSource(0.0, -5.0, f)
         rx = AcousticReceiver(100.0, -10.0)
         r = eigenrays(pm, tx, rx)
        abs(r[5].phasor)   # amplitude for the 5th path
end

ForwardDiff.derivative(g, 1000.0)
```

will yield the derivative `-9.851161055596751e-9`.

**Comment by mchitre** [comment]
And no, it shouldn't take so long to run. On my machine, first run (compilation) takes about 9 seconds, and subsequent runs about 70 ms:
```julia
julia> @time ForwardDiff.derivative(g, 1000.0)
  9.128225 seconds (15.52 M allocations: 981.574 MiB, 2.64% gc time, 47.50% compilation time)
-9.851161055596751e-9

julia> @time ForwardDiff.derivative(g, 1000.0)
  0.070012 seconds (668.07 k allocations: 90.960 MiB, 36.60% gc time)
-9.851161055596751e-9
```

**Comment by mchitre** [comment]
@almcleanuk did you resolve this problem?

**Comment by mchitre** [comment]
Closing this for now, since I don't see any concrete actions to follow up on. Should there still be a problem, please post details and re-open.

**Comment by mchitre** [comment]
At the moment, derivatives wrt θ aren't possible because of an iterative search for eigenrays over θ (issue #8). Within each search computation, θ is a constant, and hence the derivative wrt it is always zero.

To solve this, we may need a small angle Δθ expansion around the the nominal search angle θ₀, with θ = θ₀ + Δθ. Then we can take derivative wrt θ, as Δθ will be part of the computation and not a constant.
